//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventarioApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sucursales
    {
        public Sucursales()
        {
            this.Suc_producto = new HashSet<Suc_producto>();
        }
    
        public int id_sucursal { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<Suc_producto> Suc_producto { get; set; }
    }
}
